/**
 * Build-time inlined constant names for Socket CLI.
 * These are environment variable names that get inlined during build.
 */

export const INLINED_SOCKET_CLI_COANA_VERSION =
  'INLINED_SOCKET_CLI_COANA_VERSION'
export const INLINED_SOCKET_CLI_CYCLONEDX_CDXGEN_VERSION =
  'INLINED_SOCKET_CLI_CYCLONEDX_CDXGEN_VERSION'
export const INLINED_SOCKET_CLI_HOMEPAGE = 'INLINED_SOCKET_CLI_HOMEPAGE'
export const INLINED_SOCKET_CLI_LEGACY_BUILD = 'INLINED_SOCKET_CLI_LEGACY_BUILD'
export const INLINED_SOCKET_CLI_NAME = 'INLINED_SOCKET_CLI_NAME'
export const INLINED_SOCKET_CLI_PUBLISHED_BUILD =
  'INLINED_SOCKET_CLI_PUBLISHED_BUILD'
export const INLINED_SOCKET_CLI_PYTHON_BUILD_TAG =
  'INLINED_SOCKET_CLI_PYTHON_BUILD_TAG'
export const INLINED_SOCKET_CLI_PYTHON_VERSION =
  'INLINED_SOCKET_CLI_PYTHON_VERSION'
export const INLINED_SOCKET_CLI_SENTRY_BUILD = 'INLINED_SOCKET_CLI_SENTRY_BUILD'
export const INLINED_SOCKET_CLI_SYNP_VERSION = 'INLINED_SOCKET_CLI_SYNP_VERSION'
export const INLINED_SOCKET_CLI_VERSION = 'INLINED_SOCKET_CLI_VERSION'
export const INLINED_SOCKET_CLI_VERSION_HASH = 'INLINED_SOCKET_CLI_VERSION_HASH'
