#!/bin/bash
# Socket CLI Build Environment Activation Script
# Auto-generated by setup-build-toolchain.mjs

# Activate Emscripten SDK
if [ -f "/Users/jdalton/.emsdk/emsdk_env.sh" ]; then
  source "/Users/jdalton/.emsdk/emsdk_env.sh"
  echo "✓ Emscripten activated"
fi

# Add Rust to PATH
if [ -d "/Users/jdalton/.cargo/bin" ]; then
  export PATH="/Users/jdalton/.cargo/bin:$PATH"
  echo "✓ Rust activated"
fi

# Verify tools
echo ""
echo "Build environment ready:"
command -v emcc >/dev/null && echo "  ✓ emcc: $(emcc --version | head -1)"
command -v rustc >/dev/null && echo "  ✓ rustc: $(rustc --version)"
command -v python3 >/dev/null && echo "  ✓ python3: $(python3 --version)"
command -v clang >/dev/null && echo "  ✓ clang: $(clang --version | head -1)"
echo ""
