packages:
  - 'packages/*'

catalog:
  # Socket shared dependencies - define versions once, reference with catalog: protocol.
  '@socketsecurity/config': 3.0.1
  '@socketsecurity/lib': 2.3.0
  '@socketsecurity/registry': 2.0.0
  '@socketsecurity/sdk': 3.0.10
  del-cli: 6.0.0
  esbuild: 0.24.0
  postject: 1.0.0-alpha.6
  semver: 7.6.3
  which: 5.0.0
