packages:
  - packages/*

catalog:
  '@babel/core': 7.28.4
  '@babel/generator': 7.28.5
  '@babel/parser': 7.28.4
  '@babel/plugin-proposal-export-default-from': 7.27.1
  '@babel/plugin-transform-export-namespace-from': 7.27.1
  '@babel/plugin-transform-runtime': 7.28.3
  '@babel/preset-react': 7.27.1
  '@babel/preset-typescript': 7.27.1
  '@babel/runtime': 7.28.4
  '@babel/traverse': 7.28.4
  '@babel/types': 7.28.5
  '@biomejs/biome': 2.2.4
  '@coana-tech/cli': 14.12.51
  '@cyclonedx/cdxgen': 11.10.0
  '@dotenvx/dotenvx': 1.49.0
  '@eslint/compat': 1.3.2
  '@eslint/js': 9.35.0
  '@gitbeaker/rest': 43.7.0
  '@inquirer/confirm': 5.1.16
  '@inquirer/input': 4.2.2
  '@inquirer/password': 4.0.18
  '@inquirer/search': 3.1.1
  '@inquirer/select': 4.3.2
  '@npmcli/package-json': 7.0.0
  '@npmcli/promise-spawn': 8.0.3
  '@socketregistry/is-unicode-supported': 1.0.5
  '@typescript/native-preview': 7.0.0-dev.20250920.1
  '@vitest/ui': 4.0.3
  '@yarnpkg/extensions': 2.0.6
  cacache: 20.0.1
  debug: 4.4.3
  del: 8.0.1
  eslint-plugin-unicorn: 61.0.2
  fast-sort: 3.4.1
  get-east-asian-width: 1.3.0
  libnpmexec: 10.1.8
  libnpmpack: 9.0.9
  lint-staged: 15.2.11
  make-fetch-happen: 15.0.2
  nock: 14.0.10
  normalize-package-data: 8.0.0
  openapi-typescript: 7.10.1
  pacote: 21.0.1
  picomatch: 2.3.1
  spdx-correct: 3.2.0
  spdx-expression-parse: 4.0.0
  streaming-iterables: 8.0.1
  typescript: 5.9.2
  validate-npm-package-name: 6.0.2
  vite-tsconfig-paths: 5.1.4
  which: 5.0.0
  '@iarna/toml': ^2.2.5
  '@npmcli/arborist': 9.1.4
  '@npmcli/config': 10.4.0
  '@octokit/graphql': 9.0.1
  '@octokit/openapi-types': 25.1.0
  '@octokit/request-error': 7.0.0
  '@octokit/rest': 22.0.0
  '@octokit/types': 14.1.0
  '@pnpm/dependency-path': 1001.1.0
  '@pnpm/lockfile.detect-dep-types': 1001.0.13
  '@pnpm/lockfile.fs': 1001.1.17
  '@pnpm/logger': 1001.0.0
  '@sentry/node': 8.0.0
  '@socketregistry/hyrious__bun.lockb': 1.0.19
  '@socketregistry/indent-string': 1.0.14
  '@socketregistry/is-interactive': 1.0.6
  '@socketregistry/packageurl-js': 1.3.5
  '@socketregistry/yocto-spinner': 1.0.25
  '@socketsecurity/config': 3.0.1
  '@socketsecurity/registry': 2.0.2
  '@types/babel__traverse': 7.28.0
  '@types/cmd-shim': 5.0.2
  '@types/ink': 2.0.3
  '@types/js-yaml': 4.0.9
  '@types/micromatch': 4.0.9
  '@types/mock-fs': 4.13.4
  '@types/node': 24.9.2
  '@types/npm-package-arg': 6.1.4
  '@types/npmcli__arborist': 6.3.1
  '@types/npmcli__config': 6.0.3
  '@types/proc-log': 3.0.4
  '@types/react': 19.2.2
  '@types/semver': 7.7.1
  '@types/which': 3.0.4
  '@types/yargs-parser': 21.0.3
  '@typescript-eslint/parser': 8.44.1
  '@vitest/coverage-v8': 4.0.3
  '@yao-pkg/pkg': 6.8.0
  '@yarnpkg/parsers': ^3.0.3
  aggregate-error: npm:@socketregistry/aggregate-error@^1.0.15
  ajv-dist: 8.17.1
  ansi-regex: 6.1.0
  brace-expansion: 2.0.2
  browserslist: 4.25.4
  chalk-table: 1.0.2
  cmd-shim: 7.0.0
  compromise: 14.14.4
  del-cli: 6.0.0
  dev-null-cli: 2.0.0
  emoji-regex: 10.6.0
  es-define-property: npm:@socketregistry/es-define-property@^1.0.7
  es-set-tostringtag: npm:@socketregistry/es-set-tostringtag@^1.0.10
  esbuild: 0.25.11
  eslint: 9.35.0
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-jsdoc: 57.0.8
  eslint-plugin-n: 17.21.3
  eslint-plugin-sort-destructure-keys: 2.0.0
  fast-glob: 3.3.3
  fast-xml-parser: ^5.3.1
  function-bind: npm:@socketregistry/function-bind@^1.0.7
  globals: 16.4.0
  globalthis: npm:@socketregistry/globalthis@^1.0.8
  gopd: npm:@socketregistry/gopd@^1.0.7
  graceful-fs: 4.2.11
  has-property-descriptors: npm:@socketregistry/has-property-descriptors@^1.0.7
  has-proto: npm:@socketregistry/has-proto@^1.0.7
  has-symbols: npm:@socketregistry/has-symbols@^1.0.7
  has-tostringtag: npm:@socketregistry/has-tostringtag@^1.0.7
  hasown: npm:@socketregistry/hasown@^1.0.7
  hpagent: 1.2.0
  http2-wrapper: 2.2.1
  https-proxy-agent: 7.0.6
  husky: 9.1.7
  ignore: 7.0.5
  indent-string: npm:@socketregistry/indent-string@^1.0.14
  ink: 6.3.1
  ink-table: 3.1.0
  ink-text-input: 6.0.0
  is-core-module: npm:@socketregistry/is-core-module@^1.0.11
  isarray: npm:@socketregistry/isarray@^1.0.8
  js-yaml: npm:@zkochan/js-yaml@0.0.10
  lodash: 4.17.21
  magic-string: 0.30.19
  micromatch: 4.0.8
  mock-fs: 5.5.0
  nanotar: 0.2.0
  npm-package-arg: 13.0.0
  npm-run-all2: 8.0.4
  onnxruntime-web: 1.23.0
  open: 10.2.0
  packageurl-js: npm:@socketregistry/packageurl-js@^1.3.5
  path-parse: npm:@socketregistry/path-parse@^1.0.8
  pony-cause: 2.1.11
  postject: 1.0.0-alpha.6
  react: 19.2.0
  react-reconciler: 0.33.0
  registry-auth-token: 5.1.0
  registry-url: 7.2.0
  safe-buffer: npm:@socketregistry/safe-buffer@^1.0.9
  safer-buffer: npm:@socketregistry/safer-buffer@^1.0.10
  semver: 7.7.2
  set-function-length: npm:@socketregistry/set-function-length@^1.0.10
  shell-quote: npm:shell-quote@^1.8.3
  side-channel: npm:@socketregistry/side-channel@^1.0.10
  ssri: 12.0.0
  string-width: 8.1.0
  string_decoder: 0.10.31
  synp: 1.9.14
  tar-stream: 3.1.7
  taze: 19.6.0
  terminal-link: 2.1.1
  tiny-colors: 2.1.3
  trash: 10.0.0
  type-coverage: 2.29.7
  typedarray: npm:@socketregistry/typedarray@^1.0.8
  typescript-eslint: 8.44.1
  undici: 6.21.3
  unplugin-purge-polyfills: 0.1.0
  vite: 7.1.12
  vitest: 4.0.3
  xml2js: 0.6.2
  yaml: 2.8.1
  yargs-parser: 21.1.1
  yoctocolors-cjs: 2.1.3
  yoga-layout: 3.2.1
  zod: 4.1.8
