packages:
  - 'packages/*'

catalog:
  # Socket shared dependencies - define versions once, reference with catalog: protocol.
  '@babel/parser': 7.28.4
  '@babel/traverse': 7.28.4
  '@socketsecurity/config': 3.0.1
  '@socketsecurity/lib': 2.7.0
  '@socketsecurity/registry': 2.0.0
  '@socketsecurity/sdk': 3.0.14
  del-cli: 6.0.0
  esbuild: 0.24.0
  magic-string: 0.30.19
  postject: 1.0.0-alpha.6
  semver: 7.6.3
