{
  "openapi": "3.0.0",
  "info": {
    "description": "Specification of the Socket API endpoints",
    "title": "API Endpoints",
    "version": "0"
  },
  "servers": [
    {
      "url": "https://api.socket.dev/v0"
    }
  ],
  "tags": [
    {
      "name": "Packages"
    },
    {
      "name": "Dependencies"
    },
    {
      "name": "Alerts"
    },
    {
      "name": "Full Scans"
    },
    {
      "name": "Diff Scans"
    },
    {
      "name": "Triage"
    },
    {
      "name": "Repos"
    },
    {
      "name": "Repo Labels"
    },
    {
      "name": "Threat Feed"
    },
    {
      "name": "Org Snapshots"
    },
    {
      "name": "Security Policy"
    },
    {
      "name": "License Policy"
    },
    {
      "name": "Org Settings"
    },
    {
      "name": "Audit Log"
    },
    {
      "name": "API Tokens"
    },
    {
      "name": "Metadata"
    },
    {
      "name": "Deprecated"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Organization Tokens can be passed as a Bearer token"
      },
      "basicAuth": {
        "type": "http",
        "scheme": "basic",
        "description": "Organization Tokens can be passed as the user field in basic auth"
      }
    }
  },
  "paths": {
    "/purl": {
      "post": {
        "tags": [
          "Packages"
        ],
        "summary": "Get Packages by PURL",
        "operationId": "batchPackageFetch",
        "security": [
          {
            "bearerAuth": [
              "packages:list"
            ]
          },
          {
            "basicAuth": [
              "packages:list"
            ]
          }
        ],
        "description": "Batch retrieval of package metadata and alerts by PURL strings. Compatible witch CycloneDX reports.\n\nPackage URLs (PURLs) are an ecosystem agnostic way to identify packages.\nCycloneDX SBOMs use the purl format to identify components.\nThis endpoint supports fetching metadata and alerts for multiple packages at once by passing an array of purl strings, or by passing an entire CycloneDX report.\n\nMore information on purl and CycloneDX:\n\n- [`purl` Spec](https://github.[...]"
      }
    },
    "/dependencies/search": {
      "post": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Search dependencies",
        "operationId": "searchDependencies",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "Search for any dependency that is being used in your organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- No Scopes Required, but authentication is required"
      }
    },
    "/dependencies/upload": {
      "post": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Create a snapshot of all dependencies from manifest information",
        "deprecated": true,
        "operationId": "createDependenciesSnapshot",
        "security": [
          {
            "bearerAuth": [
              "report:write"
            ]
          },
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.**\n\nUpload a set of manifest or lockfiles to get your dependency tree analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: \"requirements.txt\", \"package.json\", \"folder/package.json\", and \"deep/nested/folder/package.json\".\n\nThis endpoint consumes 100 units of your quota.\n\nThis e[...]"
      }
    },
    "/orgs/{org_slug}/full-scans": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "List full scans",
        "operationId": "getOrgFullScanList",
        "security": [
          {
            "bearerAuth": [
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Returns a paginated list of all full scans in an org, excluding SBOM artifacts.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      },
      "post": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Create full scan",
        "operationId": "CreateOrgFullScan",
        "security": [
          {
            "bearerAuth": [
              "full-scans:create"
            ]
          },
          {
            "basicAuth": [
              "full-scans:create"
            ]
          }
        ],
        "description": "Create a full scan from a set of package manifest files. Returns a full scan including all SBOM artifacts.\n\nTo get a list of supported filetypes that can be uploaded in a full-scan, see the [Get supported file types](/reference/getsupportedfiles) endpoint.\n\nThe maximum number of files you can upload at a time is 5000 and each file can be no bigger than 67 MB.\n\n**Query Parameters:**\n- `scan_type` (optional): The type of scan to perform. Defaults to 'socket'. Must be[...]"
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Stream full scan",
        "operationId": "getOrgFullScan",
        "security": [
          {
            "bearerAuth": [
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Stream all SBOM artifacts for a full scan.\n\nThis endpoint returns the latest, available alert data for artifacts in the full scan (stale while revalidate).\nActively running analysis will be returned when available on subsequent runs.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      },
      "delete": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Delete full scan",
        "operationId": "deleteOrgFullScan",
        "security": [
          {
            "bearerAuth": [
              "full-scans:delete"
            ]
          },
          {
            "basicAuth": [
              "full-scans:delete"
            ]
          }
        ],
        "description": "Delete an existing full scan.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:delete"
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}/metadata": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Get full scan metadata",
        "operationId": "getOrgFullScanMetadata",
        "security": [
          {
            "bearerAuth": [
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Get metadata for a single full scan\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      }
    },
    "/orgs/{org_slug}/full-scans/diff": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Diff Full Scans",
        "deprecated": true,
        "operationId": "GetOrgDiffScan",
        "security": [
          {
            "bearerAuth": [
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.**\n\nGet the difference between two existing Full Scans. The results are not persisted.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      }
    },
    "/orgs/{org_slug}/full-scans/diff/gfm": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "SCM Comment for Scan Diff",
        "deprecated": true,
        "operationId": "GetOrgFullScanDiffGfm",
        "security": [
          {
            "bearerAuth": [
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.**\n\nGet the dependency overview and dependency alert comments in GitHub flavored markdown between the diff between two existing full scans.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      }
    },
    "/orgs/{org_slug}/export/cdx/{id}": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Export CycloneDX SBOM (Beta)",
        "operationId": "exportCDX",
        "security": [
          {
            "bearerAuth": [
              "report:read"
            ]
          },
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Export a Socket SBOM as a CycloneDX SBOM\n\nSupported ecosystems:\n\n- crates\n- go\n- maven\n- npm\n- nuget\n- pypi\n- rubygems\n- spdx\n- cdx\n\nUnsupported ecosystems are filtered from the export.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/orgs/{org_slug}/export/spdx/{id}": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Export SPDX SBOM (Beta)",
        "operationId": "exportSPDX",
        "security": [
          {
            "bearerAuth": [
              "report:read"
            ]
          },
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Export a Socket SBOM as a SPDX SBOM\n\nSupported ecosystems:\n\n- crates\n- go\n- maven\n- npm\n- nuget\n- pypi\n- rubygems\n- spdx\n- cdx\n\nUnsupported ecosystems are filtered from the export.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/orgs/{org_slug}/diff-scans": {
      "get": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "List diff scans",
        "operationId": "listOrgDiffScans",
        "security": [
          {
            "bearerAuth": [
              "diff-scans:list"
            ]
          },
          {
            "basicAuth": [
              "diff-scans:list"
            ]
          }
        ],
        "description": "Returns a paginated list of all diff scans in an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- diff-scans:list"
      }
    },
    "/orgs/{org_slug}/diff-scans/{diff_scan_id}": {
      "get": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "Get diff scan",
        "operationId": "getDiffScanById",
        "security": [
          {
            "bearerAuth": [
              "diff-scans:list"
            ]
          },
          {
            "basicAuth": [
              "diff-scans:list"
            ]
          }
        ],
        "description": "Get the difference between two full scans from an existing diff scan resource.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- diff-scans:list"
      },
      "delete": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "Delete diff scan",
        "operationId": "deleteOrgDiffScan",
        "security": [
          {
            "bearerAuth": [
              "diff-scans:delete"
            ]
          },
          {
            "basicAuth": [
              "diff-scans:delete"
            ]
          }
        ],
        "description": "Delete an existing diff scan.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- diff-scans:delete"
      }
    },
    "/orgs/{org_slug}/diff-scans/{diff_scan_id}/gfm": {
      "get": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "SCM Comment for Diff Scan",
        "operationId": "GetDiffScanGfm",
        "security": [
          {
            "bearerAuth": [
              "diff-scans:list"
            ]
          },
          {
            "basicAuth": [
              "diff-scans:list"
            ]
          }
        ],
        "description": "Get the dependency overview and dependency alert comments in GitHub flavored markdown for an existing diff scan.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- diff-scans:list"
      }
    },
    "/orgs/{org_slug}/diff-scans/from-repo/{repo_slug}": {
      "post": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "Create diff scan from repository HEAD full-scan",
        "operationId": "createOrgRepoDiff",
        "security": [
          {
            "bearerAuth": [
              "repo:list",
              "diff-scans:create",
              "full-scans:create"
            ]
          },
          {
            "basicAuth": [
              "repo:list",
              "diff-scans:create",
              "full-scans:create"
            ]
          }
        ],
        "description": "Create a diff scan between the repository's current HEAD full scan and a new full scan from uploaded manifest files.\nReturns metadata about the diff scan. Once the diff scan is created, fetch the diff scan from\nthe [api_url](/reference/getDiffScanById) URL to get the contents of the diff.\n\nThe maximum number of files you can upload at a time is 5000 and each file can be no bigger than 67 MB.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the[...]"
      }
    },
    "/orgs/{org_slug}/diff-scans/from-ids": {
      "post": {
        "tags": [
          "Diff Scans"
        ],
        "summary": "Create diff scan from full scan IDs",
        "operationId": "createOrgDiffScanFromIds",
        "security": [
          {
            "bearerAuth": [
              "diff-scans:create",
              "full-scans:list"
            ]
          },
          {
            "basicAuth": [
              "diff-scans:create",
              "full-scans:list"
            ]
          }
        ],
        "description": "Create a diff scan from two existing full scan IDs. The full scans must be in the same repository.\nReturns metadata about the diff scan. Once the diff scan is created, fetch the diff scan from\nthe [api_url](/reference/getDiffScanById) URL to get the contents of the diff.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n      - diff-scans:create\n- full-scans:list"
      }
    },
    "/orgs/{org_slug}/triage/alerts": {
      "get": {
        "tags": [
          "Triage"
        ],
        "summary": "List Org Alert Triage",
        "operationId": "getOrgTriage",
        "security": [
          {
            "bearerAuth": [
              "triage:alerts-list"
            ]
          },
          {
            "basicAuth": [
              "triage:alerts-list"
            ]
          }
        ],
        "description": "Get alert triage actions for an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- triage:alerts-list"
      },
      "post": {
        "tags": [
          "Triage"
        ],
        "summary": "Update Org Alert Triage",
        "operationId": "updateOrgAlertTriage",
        "security": [
          {
            "bearerAuth": [
              "triage:alerts-update"
            ]
          },
          {
            "basicAuth": [
              "triage:alerts-update"
            ]
          }
        ],
        "description": "Update triage actions on organizaton alerts.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- triage:alerts-update"
      }
    },
    "/orgs/{org_slug}/repos": {
      "get": {
        "tags": [
          "Repos"
        ],
        "summary": "List repositories",
        "operationId": "getOrgRepoList",
        "security": [
          {
            "bearerAuth": [
              "repo:list"
            ]
          },
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Lists repositories for the specified organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      },
      "post": {
        "tags": [
          "Repos"
        ],
        "summary": "Create repository",
        "operationId": "createOrgRepo",
        "security": [
          {
            "bearerAuth": [
              "repo:create"
            ]
          },
          {
            "basicAuth": [
              "repo:create"
            ]
          }
        ],
        "description": "Create a repository.\n\nRepos collect Full scans and Diff scans and are typically associated with a git repo.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:create"
      }
    },
    "/orgs/{org_slug}/repos/{repo_slug}": {
      "get": {
        "tags": [
          "Repos"
        ],
        "summary": "Get repository",
        "operationId": "getOrgRepo",
        "security": [
          {
            "bearerAuth": [
              "repo:list"
            ]
          },
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Retrieve a repository associated with an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      },
      "post": {
        "tags": [
          "Repos"
        ],
        "summary": "Update repository",
        "operationId": "updateOrgRepo",
        "security": [
          {
            "bearerAuth": [
              "repo:update"
            ]
          },
          {
            "basicAuth": [
              "repo:update"
            ]
          }
        ],
        "description": "Update details of an existing repository.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:update"
      },
      "delete": {
        "tags": [
          "Repos"
        ],
        "summary": "Delete repository",
        "operationId": "deleteOrgRepo",
        "security": [
          {
            "bearerAuth": [
              "repo:delete"
            ]
          },
          {
            "basicAuth": [
              "repo:delete"
            ]
          }
        ],
        "description": "Delete a single repository and all of its associated Full scans and Diff scans.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:delete"
      }
    },
    "/orgs/{org_slug}/repos/labels/{label_id}/associate": {
      "post": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Associate repository label (beta)",
        "operationId": "associateOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:update"
            ]
          },
          {
            "basicAuth": [
              "repo-label:update"
            ]
          }
        ],
        "description": "Associate a repository label with a repository.\n\nLabels can be used to group and organize repositories and to apply security/license policies.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:update"
      }
    },
    "/orgs/{org_slug}/repos/labels": {
      "post": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Create repository label (beta)",
        "operationId": "createOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:create"
            ]
          },
          {
            "basicAuth": [
              "repo-label:create"
            ]
          }
        ],
        "description": "Create a repository label.\n\nLabels can be used to group and organize repositories and to apply security/license policies.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:create"
      },
      "get": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "List repository labels (beta)",
        "operationId": "getOrgRepoLabelList",
        "security": [
          {
            "bearerAuth": [
              "repo-label:list"
            ]
          },
          {
            "basicAuth": [
              "repo-label:list"
            ]
          }
        ],
        "description": "Lists repository labels for the specified organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:list"
      }
    },
    "/orgs/{org_slug}/repos/labels/{label_id}": {
      "delete": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Delete repository label (beta)",
        "operationId": "deleteOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:delete"
            ]
          },
          {
            "basicAuth": [
              "repo-label:delete"
            ]
          }
        ],
        "description": "Delete a repository label and all of its associations (repositories, security policy, license policy, etc.).\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:delete"
      },
      "get": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Get repository label (beta)",
        "operationId": "getOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:list"
            ]
          },
          {
            "basicAuth": [
              "repo-label:list"
            ]
          }
        ],
        "description": "Retrieve a repository label associated with an organization and label ID.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:list"
      },
      "put": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Update repository label (beta)",
        "operationId": "updateOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:update"
            ]
          },
          {
            "basicAuth": [
              "repo-label:update"
            ]
          }
        ],
        "description": "Update a repository label name.\n\nLabels can be used to group and organize repositories and to apply security/license policies.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:update"
      }
    },
    "/orgs/{org_slug}/repos/labels/{label_id}/label-setting": {
      "delete": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Delete repository label setting (beta)",
        "operationId": "deleteOrgRepoLabelSetting",
        "security": [
          {
            "bearerAuth": [
              "repo-label:update"
            ]
          },
          {
            "basicAuth": [
              "repo-label:update"
            ]
          }
        ],
        "description": "Delete the setting (e.g. security/license policy) for a repository label.\n\n\nNote that repository label settings currently only support `issueRules`\nand `issueRulesPolicyDefault`. A policy is considered \"active\" for\na given repository label if the `issueRulesPolicyDefault` is set,\nand inactive when not set. `issueRules` can be used to further\nrefine the alert triage strategy.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following o[...]"
      },
      "get": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Get repository label setting (beta)",
        "operationId": "getOrgRepoLabelSetting",
        "security": [
          {
            "bearerAuth": [
              "repo-label:list"
            ]
          },
          {
            "basicAuth": [
              "repo-label:list"
            ]
          }
        ],
        "description": "Retrieve the setting (e.g. security/license policy) for a repository label.\n\n\nNote that repository label settings currently only support `issueRules`\nand `issueRulesPolicyDefault`. A policy is considered \"active\" for\na given repository label if the `issueRulesPolicyDefault` is set,\nand inactive when not set. `issueRules` can be used to further\nrefine the alert triage strategy.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following[...]"
      },
      "put": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Update repository label setting (beta)",
        "operationId": "updateOrgRepoLabelSetting",
        "security": [
          {
            "bearerAuth": [
              "repo-label:update"
            ]
          },
          {
            "basicAuth": [
              "repo-label:update"
            ]
          }
        ],
        "description": "Update the setting (e.g. security/license policy) for a repository label.\n\n\nNote that repository label settings currently only support `issueRules`\nand `issueRulesPolicyDefault`. A policy is considered \"active\" for\na given repository label if the `issueRulesPolicyDefault` is set,\nand inactive when not set. `issueRules` can be used to further\nrefine the alert triage strategy.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following o[...]"
      }
    },
    "/orgs/{org_slug}/repos/labels/{label_id}/disassociate": {
      "post": {
        "tags": [
          "Repo Labels"
        ],
        "summary": "Disassociate repository label (beta)",
        "operationId": "disassociateOrgRepoLabel",
        "security": [
          {
            "bearerAuth": [
              "repo-label:update"
            ]
          },
          {
            "basicAuth": [
              "repo-label:update"
            ]
          }
        ],
        "description": "Disassociate a repository label from a repository.\n\nLabels can be used to group and organize repositories and to apply security/license policies.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo-label:update"
      }
    },
    "/orgs/{org_slug}/settings/integrations/{integration_id}/events": {
      "get": {
        "tags": [
          "Org Settings"
        ],
        "summary": "Get integration events",
        "operationId": "getIntegrationEvents",
        "security": [
          {
            "bearerAuth": [
              "integration:list"
            ]
          },
          {
            "basicAuth": [
              "integration:list"
            ]
          }
        ],
        "description": "This endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- integration:list"
      }
    },
    "/orgs/{org_slug}/settings/security-policy": {
      "get": {
        "tags": [
          "Security Policy"
        ],
        "summary": "Get Organization Security Policy",
        "operationId": "getOrgSecurityPolicy",
        "security": [
          {
            "bearerAuth": [
              "security-policy:read"
            ]
          },
          {
            "basicAuth": [
              "security-policy:read"
            ]
          }
        ],
        "description": "Retrieve the security policy of an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- security-policy:read"
      },
      "post": {
        "tags": [
          "Security Policy"
        ],
        "summary": "Update Security Policy",
        "operationId": "updateOrgSecurityPolicy",
        "security": [
          {
            "bearerAuth": [
              "security-policy:update"
            ]
          },
          {
            "basicAuth": [
              "security-policy:update"
            ]
          }
        ],
        "description": "Update the security policy of an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- security-policy:update"
      }
    },
    "/orgs/{org_slug}/settings/license-policy": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get Organization License Policy",
        "deprecated": true,
        "operationId": "getOrgLicensePolicy",
        "security": [
          {
            "bearerAuth": [
              "license-policy:read"
            ]
          },
          {
            "basicAuth": [
              "license-policy:read"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/viewlicensepolicy) instead.\n\nRetrieve the license policy of an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- license-policy:read"
      },
      "post": {
        "tags": [
          "License Policy"
        ],
        "summary": "Update License Policy",
        "operationId": "updateOrgLicensePolicy",
        "security": [
          {
            "bearerAuth": [
              "license-policy:update"
            ]
          },
          {
            "basicAuth": [
              "license-policy:update"
            ]
          }
        ],
        "description": "Set the organization's license policy\n\n      ## License policy schema\n\n```json\n{\n  allow?: Array<string>\n  warn?: Array<string>\n  options?: Array<string>\n}\n```\n\nElements of the `allow` and `warn` arrays strings representing items which should be allowed, or which should trigger a warning; license data found in package which not present in either array will produce a license violation (effectively a \"hard\" error). For example, to allow Apache-2.0 and MIT to t[...]"
      }
    },
    "/orgs/{org_slug}/settings/license-policy/view": {
      "get": {
        "tags": [
          "License Policy"
        ],
        "summary": "Get License Policy (Beta)",
        "operationId": "viewLicensePolicy",
        "security": [
          {
            "bearerAuth": [
              "license-policy:read"
            ]
          },
          {
            "basicAuth": [
              "license-policy:read"
            ]
          }
        ],
        "description": "Returns an organization's license policy including allow, warn, monitor, and deny categories.\nThe deny category contains all licenses that are not explicitly categorized as allow, warn, or monitor.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- license-policy:read"
      }
    },
    "/orgs/{org_slug}/settings/socket-basics": {
      "get": {
        "tags": [
          "Org Settings"
        ],
        "summary": "Get Socket Basics configuration, including toggles for the various tools it supports.",
        "operationId": "getSocketBasicsConfig",
        "security": [
          {
            "bearerAuth": [
              "socket-basics:read"
            ]
          },
          {
            "basicAuth": [
              "socket-basics:read"
            ]
          }
        ],
        "description": "Socket Basics is a CI/CD security scanning suite that runs on your source code, designed to complement Socket SCA and provide full coverage.\n\n- **SAST** - Find issues and risks with your code via static analysis using best in class Open Source tools\n- **Secret Scanning** - Detected potentially leaked secrets and credentials within your code\n- **Container Security** - Docker image and Dockerfile vulnerability scanning\n\nThis endpoint consumes 1 unit of your quota.\n\n[...]"
      }
    },
    "/orgs/{org_slug}/historical/alerts": {
      "get": {
        "tags": [
          "Alerts"
        ],
        "summary": "List historical alerts (Beta)",
        "operationId": "historicalAlertsList",
        "security": [
          {
            "bearerAuth": [
              "historical:alerts-list"
            ]
          },
          {
            "basicAuth": [
              "historical:alerts-list"
            ]
          }
        ],
        "description": "List historical alerts.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- historical:alerts-list"
      }
    },
    "/orgs/{org_slug}/historical/alerts/trend": {
      "get": {
        "tags": [
          "Alerts"
        ],
        "summary": "Trend of historical alerts (Beta)",
        "operationId": "historicalAlertsTrend",
        "security": [
          {
            "bearerAuth": [
              "historical:alerts-trend"
            ]
          },
          {
            "basicAuth": [
              "historical:alerts-trend"
            ]
          }
        ],
        "description": "Trend analytics of historical alerts.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- historical:alerts-trend"
      }
    },
    "/orgs/{org_slug}/historical/dependencies/trend": {
      "get": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Trend of historical dependencies (Beta)",
        "operationId": "historicalDependenciesTrend",
        "security": [
          {
            "bearerAuth": [
              "historical:dependencies-trend"
            ]
          },
          {
            "basicAuth": [
              "historical:dependencies-trend"
            ]
          }
        ],
        "description": "Trend analytics of historical dependencies.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- historical:dependencies-trend"
      }
    },
    "/orgs/{org_slug}/historical/snapshots": {
      "get": {
        "tags": [
          "Org Snapshots"
        ],
        "summary": "List details of periodic historical data snapshots (Beta)",
        "operationId": "historicalSnapshotsList",
        "security": [
          {
            "bearerAuth": [
              "historical:snapshots-list"
            ]
          },
          {
            "basicAuth": [
              "historical:snapshots-list"
            ]
          }
        ],
        "description": "This API endpoint is used to list the details of historical snapshots.\nSnapshots of organization data are taken periodically, and each historical snapshot record contains high-level overview metrics about the data that was collected.\nOther [Historical Data Endpoints](/reference/historical-data-endpoints) can be used to fetch the raw data associated with each snapshot.\n\nHistorical snapshots contain details and raw data for the following resources:\n\n- Repositories\n- [...]"
      },
      "post": {
        "tags": [
          "Org Snapshots"
        ],
        "summary": "Start historical data snapshot job (Beta)",
        "operationId": "historicalSnapshotsStart",
        "security": [
          {
            "bearerAuth": [
              "historical:snapshots-start"
            ]
          },
          {
            "basicAuth": [
              "historical:snapshots-start"
            ]
          }
        ],
        "description": "This API endpoint is used to start a historical snapshot job.\nWhile snapshots are typically taken at least once a day, this endpoint can be used to start an \"on demand\" snapshot job to ensure the latest data is collected and stored for historical purposes.\n\nAn historical snapshot will contain details and raw data for the following resources:\n\n- Repositories\n- Alerts\n- Dependencies\n- Artifacts\n- Users\n- Settings\n\nHistorical snapshot data is bucketed to the ne[...]"
      }
    },
    "/orgs/{org_slug}/audit-log": {
      "get": {
        "tags": [
          "Audit Log"
        ],
        "summary": "Get Audit Log Events",
        "operationId": "getAuditLogEvents",
        "security": [
          {
            "bearerAuth": [
              "audit-log:list"
            ]
          },
          {
            "basicAuth": [
              "audit-log:list"
            ]
          }
        ],
        "description": "Paginated list of audit log events.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- audit-log:list"
      }
    },
    "/orgs/{org_slug}/api-tokens": {
      "post": {
        "tags": [
          "API Tokens"
        ],
        "summary": "Create API Token",
        "operationId": "postAPIToken",
        "security": [
          {
            "bearerAuth": [
              "api-tokens:create"
            ]
          },
          {
            "basicAuth": [
              "api-tokens:create"
            ]
          }
        ],
        "description": "Create an API Token. The API Token created must use a subset of permissions the API token creating them.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- api-tokens:create"
      },
      "get": {
        "tags": [
          "API Tokens"
        ],
        "summary": "List API Tokens",
        "operationId": "getAPITokens",
        "security": [
          {
            "bearerAuth": [
              "api-tokens:list"
            ]
          },
          {
            "basicAuth": [
              "api-tokens:list"
            ]
          }
        ],
        "description": "List all API Tokens.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- api-tokens:list"
      }
    },
    "/orgs/{org_slug}/api-tokens/update": {
      "post": {
        "tags": [
          "API Tokens"
        ],
        "summary": "Update API Token",
        "operationId": "postAPITokenUpdate",
        "security": [
          {
            "bearerAuth": [
              "api-tokens:create"
            ]
          },
          {
            "basicAuth": [
              "api-tokens:create"
            ]
          }
        ],
        "description": "Update an API Token. The API Token created must use a subset of permissions the API token creating them.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- api-tokens:create"
      }
    },
    "/orgs/{org_slug}/api-tokens/rotate": {
      "post": {
        "tags": [
          "API Tokens"
        ],
        "summary": "Rotate API Token",
        "operationId": "postAPITokensRotate",
        "security": [
          {
            "bearerAuth": [
              "api-tokens:rotate"
            ]
          },
          {
            "basicAuth": [
              "api-tokens:rotate"
            ]
          }
        ],
        "description": "Rotate an API Token\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- api-tokens:rotate"
      }
    },
    "/orgs/{org_slug}/api-tokens/revoke": {
      "post": {
        "tags": [
          "API Tokens"
        ],
        "summary": "Revoke API Token",
        "operationId": "postAPITokensRevoke",
        "security": [
          {
            "bearerAuth": [
              "api-tokens:revoke"
            ]
          },
          {
            "basicAuth": [
              "api-tokens:revoke"
            ]
          }
        ],
        "description": "Revoke an API Token\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- api-tokens:revoke"
      }
    },
    "/orgs/{org_slug}/supported-files": {
      "get": {
        "tags": [
          "Metadata",
          "Full Scans",
          "Diff Scans"
        ],
        "summary": "Get supported file types",
        "operationId": "getSupportedFiles",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "Get a list of supported files for full scan generation.\nFiles are categorized first by environment (e.g. NPM or PyPI), then by name.\n\nFiles whose names match the patterns returned by this endpoint can be uploaded for report generation.\nExamples of supported filenames include `package.json`, `package-lock.json`, and `yarn.lock`.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- No Scopes Required, but authentic[...]"
      }
    },
    "/threat-feed": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get Threat Feed Items (Deprecated)",
        "deprecated": true,
        "operationId": "getThreatFeedItems",
        "security": [
          {
            "bearerAuth": [
              "threat-feed:list"
            ]
          },
          {
            "basicAuth": [
              "threat-feed:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/getorgthreatfeeditems) instead.\n\nPaginated list of threat feed items.\n\nThis endpoint requires an Enterprise Plan with Threat Feed add-on. [Contact](https://socket.dev/demo?utm_source=api-docs&utm_medium=referral&utm_campaign=tracking) our sales team for more details.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- [...]"
      }
    },
    "/orgs/{org_slug}/threat-feed": {
      "get": {
        "tags": [
          "Threat Feed"
        ],
        "summary": "Get Threat Feed Items (Beta)",
        "operationId": "getOrgThreatFeedItems",
        "security": [
          {
            "bearerAuth": [
              "threat-feed:list"
            ]
          },
          {
            "basicAuth": [
              "threat-feed:list"
            ]
          }
        ],
        "description": "Paginated list of threats, sorted by updated_at by default. Set updated_after to the unix timestamp of your last sync while sorting by updated_at to synchronize all new or updated threats in the feed.\n\nThis endpoint requires an Enterprise Plan with Threat Feed add-on. [Contact](https://socket.dev/demo?utm_source=api-docs&utm_medium=referral&utm_campaign=tracking) our sales team for more details.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires t[...]"
      }
    },
    "/license-policy": {
      "post": {
        "tags": [
          "License Policy"
        ],
        "summary": "License Policy (Beta)",
        "operationId": "licensePolicy",
        "security": [
          {
            "bearerAuth": [
              "packages:list",
              "license-policy:read"
            ]
          },
          {
            "basicAuth": [
              "packages:list",
              "license-policy:read"
            ]
          }
        ],
        "description": "Compare the license data found for a list of packages (given as PURL strings) with the contents of a configurable license policy,\n    returning information about license data which does not comply with the license allow list.\n\n    ## Example request body:\n\n    ```json\n    {\n      \"components\": [\n        {\n          \"purl\": \"pkg:npm/lodash@4.17.21\"\n        },\n        {\n          \"purl\": \"pkg:npm/lodash@4.14.1\"\n        }\n      ],\n      \"allow\": [\[...]"
      }
    },
    "/saturate-license-policy": {
      "post": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Saturate License Policy (Legacy)",
        "deprecated": true,
        "operationId": "saturateLicensePolicy",
        "security": [
          {
            "bearerAuth": [
              "packages:list"
            ]
          },
          {
            "basicAuth": [
              "packages:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/updateorglicensepolicy) instead.\n\nGet the \"saturated\" version of a license policy's allow list, filling in the entire set of allowed\nlicense data. For example, the saturated form of a license allow list which only specifies that\nlicenses in the tier \"maximal copyleft\" are allowed is shown below (note the expanded `allowedStrings` property):\n\n```json\n{\n  \"allowedAppr[...]"
      }
    },
    "/license-metadata": {
      "post": {
        "tags": [
          "Metadata",
          "License Policy"
        ],
        "summary": "License Metadata",
        "operationId": "licenseMetadata",
        "security": [],
        "description": "For an array of license identifiers or names (short form SPDX identifiers, or long form license names),\n    returns an array of metadata for the corresponding license, if the license is recognized. If the query\n    parameter `includetext=true` is set, the returned metadata will also include the license text.\n\n\n    ## Example request body:\n\n    ```json\n    [\n      \"Apache-2.0\",\n      \"BSD Zero Clause License\"\n    ]\n    ```\n\n\n    ## Return value\n\n    ``[...]"
      }
    },
    "/alert-types": {
      "post": {
        "tags": [
          "Metadata",
          "Full Scans",
          "Diff Scans"
        ],
        "summary": "Alert Types Metadata",
        "operationId": "alertTypes",
        "security": [],
        "description": "For an array of alert type identifiers, returns metadata for each alert type. Optionally, specify a language via the 'language' query parameter.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:"
      }
    },
    "/openapi": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "summary": "Returns the OpenAPI definition",
        "operationId": "getOpenAPI",
        "security": [],
        "description": "Retrieve the API specification in an Openapi JSON format.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:"
      }
    },
    "/openapi.json": {
      "get": {
        "tags": [
          "Metadata"
        ],
        "summary": "Returns the OpenAPI definition",
        "operationId": "getOpenAPIJSON",
        "security": [],
        "description": "Retrieve the API specification in an Openapi JSON format.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:"
      }
    },
    "/quota": {
      "get": {
        "tags": [
          "API Tokens"
        ],
        "summary": "Get quota",
        "operationId": "getQuota",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "Get your current API quota. You can use this endpoint to prevent doing requests that might spend all your quota.\n\nThis endpoint consumes 0 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- No Scopes Required, but authentication is required"
      }
    },
    "/organizations": {
      "get": {
        "tags": [
          "API Tokens"
        ],
        "summary": "List organizations",
        "operationId": "getOrganizations",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "Get information on the current organizations associated with the API token.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- No Scopes Required, but authentication is required"
      }
    },
    "/settings": {
      "post": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Calculate settings",
        "deprecated": true,
        "operationId": "postSettings",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/updateorgsecuritypolicy) instead.\n\nGet current settings for the requested organizations and default settings to allow deferrals.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- No Scopes Required, but authentication is required"
      }
    },
    "/report/supported": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get supported files for report",
        "deprecated": true,
        "operationId": "getReportSupportedFiles",
        "security": [],
        "description": "**This endpoint is deprecated.** Deprecated since 2023-01-15. Use the [successor version](https://docs.socket.dev/reference/getsupportedfiles) instead.\n\nThis route has been moved to the `orgs/{org_slug}/supported-files` endpoint.\n\nGet a list of supported files for project report generation.\nFiles are categorized first by environment (e.g. NPM or PyPI), then by name.\n\nFiles whose names match the patterns returned by this endpoint can be uploaded for report generatio[...]"
      }
    },
    "/report/delete/{id}": {
      "delete": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Delete a report",
        "deprecated": true,
        "operationId": "deleteReport",
        "security": [
          {
            "bearerAuth": [
              "report:write"
            ]
          },
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference) instead.\n\nDeprecated: Use `/orgs/{org_slug}/full-scans` instead. Delete a specific project report generated with the GitHub app.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:write"
      }
    },
    "/report/list": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get list of reports",
        "deprecated": true,
        "operationId": "getReportList",
        "security": [
          {
            "bearerAuth": [
              "report:list"
            ]
          },
          {
            "basicAuth": [
              "report:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference) instead.\n\nDeprecated: Use `/orgs/{org_slug}/full-scans` instead. Get all your project reports generated with the GitHub app.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:list"
      }
    },
    "/report/upload": {
      "put": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Create a report",
        "deprecated": true,
        "operationId": "createReport",
        "security": [
          {
            "bearerAuth": [
              "report:write"
            ]
          },
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/createorgfullscan) instead.\n\nDeprecated: Use `/orgs/{org_slug}/full-scans` instead.\n\nUpload a lockfile to get your project analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: `package.json`, `folder/package.json` and `dee[...]"
      }
    },
    "/report/view/{id}": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "View a report",
        "deprecated": true,
        "operationId": "getReport",
        "security": [
          {
            "bearerAuth": [
              "report:read"
            ]
          },
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/getorgfullscan) instead.\n\nDeprecated: Use `/orgs/{org_slug}/full-scans` instead. Get all the issues, packages, and scores related to an specific project report.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/repo/list": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "List GitHub repositories",
        "deprecated": true,
        "operationId": "getRepoList",
        "security": [
          {
            "bearerAuth": [
              "repo:list"
            ]
          },
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/getorgrepolist) instead.\n\nDeprecated: Use `/orgs/{org_slug}/repos` instead. Get all GitHub repositories associated with a Socket org.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      }
    },
    "/npm/{package}/{version}/issues": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get issues by package",
        "deprecated": true,
        "operationId": "getIssuesByNPMPackage",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference) instead.\n\nGet all the issues related with a particular npm package version.\nThis endpoint returns the issue type, location, and additional details related to each issue in the `props` attribute.\n\nYou can [see here](https://socket.dev/alerts) the full list of issues.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n-[...]"
      }
    },
    "/npm/{package}/{version}/score": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get score by package",
        "deprecated": true,
        "operationId": "getScoreByNPMPackage",
        "security": [
          {
            "bearerAuth": []
          },
          {
            "basicAuth": []
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/batchpackagefetch) instead.\n\nGet all the scores and metrics by category that are used to evaluate the package version.\n\n- depscore: The average of all score factors. (0-1)\n- supplyChainRisk: Score factors relating to supply chain security (0-1)\n- downloadCount: The number of downloads for the package. Higher downloads contribute to a higher score.\n- supplyChainRiskIssueLo[...]"
      }
    },
    "/analytics/org/{filter}": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get organization analytics (unstable)",
        "deprecated": true,
        "operationId": "getOrgAnalytics",
        "security": [
          {
            "bearerAuth": [
              "report:write"
            ]
          },
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/historicalalertstrend) instead.\n\nPlease implement against the [Historical dependencies](/reference/historicaldependenciestrend) or [Historical alerts](/reference/historicalalertstrend) endpoints.\n\nGet analytics data regarding the number of alerts found across all active repositories.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org [...]"
      }
    },
    "/analytics/repo/{name}/{filter}": {
      "get": {
        "tags": [
          "Deprecated"
        ],
        "summary": "Get repository analytics",
        "deprecated": true,
        "operationId": "getRepoAnalytics",
        "security": [
          {
            "bearerAuth": [
              "report:write"
            ]
          },
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "**This endpoint is deprecated.** Use the [successor version](https://docs.socket.dev/reference/historicalalertstrend) instead.\n\nPlease implement against the [Historical dependencies](/reference/historicaldependenciestrend) or [Historical alerts](/reference/historicalalertstrend) endpoints.\n\nGet analytics data regarding the number of alerts found in a single repository.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token sc[...]"
      }
    }
  }
}