[package]
name = "socket-ai"
version = "0.1.0"
edition = "2021"
authors = ["Socket Security <hello@socket.dev>"]
description = "Unified WASM bundle for Socket CLI AI features"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
# Optimize for size.
lto = "thin"        # Thin LTO is faster than full, still effective (5-10% faster builds)
opt-level = "z"     # Optimize for size (critical for WASM)
codegen-units = 1   # Single unit for maximum optimization
strip = true        # Strip symbols for smaller WASM (saves 5-10%)
panic = "abort"     # Reduce binary size by not including unwinding code

# OPTIMIZATION: Fast dev builds for WASM (3-5x faster iteration)
# Use: cargo build --target wasm32-unknown-unknown --profile dev-wasm
[profile.dev-wasm]
inherits = "dev"
opt-level = 1           # Minimal optimization for faster builds
lto = false             # Disable LTO in dev
codegen-units = 16      # More units = faster parallel compilation
incremental = false     # Disable incremental for WASM (conflicts with embed-bitcode)
debug = false           # Disable debug info to reduce WASM size
strip = true            # Strip symbols even in dev for smaller WASM
panic = "abort"         # Reduce binary size

# Strip debug info from dependencies.
[profile.release.package."*"]
opt-level = "z"
strip = true
