#!/usr/bin/env node
// This file is replaced during installation by install.js.
console.error('Socket CLI binary not installed correctly.')
console.error('Please run: npm install -g socket')
process.exit(1)