import { defineConfig } from 'oxlint'

import { config } from '../fleet/oxlint.config.mts'

// oxlint-disable-next-line socket/no-default-export -- default export required
export default defineConfig(
  config({
    overrides: [
      {
        files: [
          '**/test/e2e/**',
          '**/test/fixtures/**',
          '**/test/helpers/**',
          '**/test/integration/**',
          '**/test/json-output-validation.mts',
          '**/test/mock-auth-oauth.mts',
          '**/test/mock-auth-session.mts',
          '**/test/mock-auth-tokens.mts',
          '**/test/mock-auth-types.mts',
          '**/test/mock-auth.mts',
          '**/test/mock-auth.test.mts',
          '**/test/mock-malware-api.mts',
          '**/test/mock-malware-api.test.mts',
          '**/test/run-with-config.mts',
          '**/test/setup.mts',
          '**/test/stubs/**',
          '**/test/unit/**',
          '**/test/util/**',
          '**/test/utils.mts',
          '**/src/command/fix/**',
          '**/src/command/manifest/**',
          '**/src/command/mcp/**',
          '**/src/command/optimize/**',
          '**/src/core/optimize/**',
          '**/src/command/package/**',
          '**/src/command/scan/**',
          '**/src/cli-entry.mts',
          '**/src/constants/agents.mts',
          '**/src/env/checksum-utils.mts',
          '**/src/flags.mts',
          '**/src/meow.mts',
          '**/src/util/basics/**',
          '**/src/util/cli/**',
          '**/src/util/command/**',
          '**/src/util/config.mts',
          '**/src/util/cve-to-ghsa.mts',
          '**/src/util/dlx/**',
          '**/src/util/dry-run/**',
          '**/src/util/ecosystem/**',
          '**/src/util/error/**',
          '**/src/util/fs/**',
          '**/src/util/sea/**',
          '**/src/util/semver.mts',
          '**/src/util/socket-yaml.mts',
          '**/src/util/socket/**',
          '**/src/util/spawn/**',
          '**/src/util/telemetry/**',
          '**/src/util/terminal/**',
          '**/.config/repo/cli/rolldown.build.mts',
          '**/.config/repo/cli/rolldown.cli.mts',
          '**/.config/repo/cli/rolldown.index.mts',
          '**/scripts/repo/**',
        ],
        rules: {
          'typescript/no-unsafe-type-assertion': 'off',
        },
      },
    ],
  }),
)
