/**
 * SEA test mode: with-tools — builds a SEA binary using Socket's own build
 * infrastructure (downloadNodeBinary + injectSeaBlob) with the full external
 * tool set bundled as SEA assets.
 */

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { existsSync, promises as fs, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { displayToolInfo } from './test-sea-shared.mts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const logger = getDefaultLogger()

/**
 * Mode: with-tools - Uses Socket infrastructure (downloadNodeBinary +
 * injectSeaBlob).
 */
export async function runWithToolsMode(platform, toolPaths) {
  logger.log('Mode: with-tools (Socket infrastructure)')
  logger.log('='.repeat(60))
  logger.log('')

  // Dynamic import Socket modules.
  const { injectSeaBlob } = await import('./sea-build-utils/builder.mts')
  const { downloadNodeBinary } = await import('./sea-build-utils/downloads.mts')

  const totalToolSize = await displayToolInfo(toolPaths)

  // Setup output.
  const entryPoint = path.join(__dirname, 'test-entry.mts')
  const outputDir = path.join(__dirname, '../dist/sea-test')
  await fs.mkdir(outputDir, { recursive: true })
  const outputPath = path.join(outputDir, `socket-with-tools-${platform}`)

  // Generate SEA config.
  const outputName = path.basename(outputPath, path.extname(outputPath))
  const configPath = path.join(
    path.dirname(outputPath),
    `sea-config-test-${outputName}.json`,
  )
  const blobPath = path.join(
    path.dirname(outputPath),
    `sea-blob-test-${outputName}.blob`,
  )

  // Build assets object with security tools.
  const assets = { __proto__: null }
  for (const [toolName, toolPath] of Object.entries(toolPaths)) {
    if (existsSync(toolPath)) {
      assets[`external-tools/${toolName}`] = toolPath
      // oxlint-disable-next-line socket/prefer-exists-sync -- reads .size for size reporting, not an existence check.
      const stats = statSync(toolPath)
      logger.log(
        `  Including ${toolName}: ${(stats.size / 1024 / 1024).toFixed(2)} MB`,
      )
    }
  }

  const config = {
    assets,
    disableExperimentalSEAWarning: true,
    main: entryPoint,
    output: blobPath,
    useCodeCache: true,
    useSnapshot: false,
  }

  await fs.writeFile(configPath, JSON.stringify(config, null, 2))
  logger.log(`Wrote SEA config: ${configPath}`)
  logger.log('')

  // Download node-smol binary.
  logger.log('Downloading node-smol binary…')
  const nodeVersion = '20251213-7cf90d2'
  const nodeBinary = await downloadNodeBinary(
    nodeVersion,
    process.platform,
    process.arch,
  )
  // Need file size for the MB report below, not just existence.
  const nodeStats = statSync(nodeBinary)
  logger.log(
    `Node binary size: ${(nodeStats.size / 1024 / 1024).toFixed(2)} MB`,
  )
  logger.log('')

  // Inject blob and VFS into binary.
  // binject will generate the blob automatically using the target binary's
  // Node.js version when --sea points to a config file.
  logger.log('Generating SEA blob and injecting into binary…')
  const cacheId = platform
  await injectSeaBlob(nodeBinary, configPath, outputPath, cacheId)

  // Get blob size after it's generated by binject.
  let blobStats
  if (existsSync(blobPath)) {
    // Need file size for the MB report below, not just existence.
    blobStats = statSync(blobPath)
    logger.log(`Blob size: ${(blobStats.size / 1024 / 1024).toFixed(2)} MB`)
  }

  // Results. Need file size for the MB report below, not just existence.
  const finalStats = statSync(outputPath)
  const finalSizeMB = finalStats.size / 1024 / 1024
  const compressionRatio = (
    (1 - finalSizeMB / ((totalToolSize + nodeStats.size) / 1024 / 1024)) *
    100
  ).toFixed(1)

  logger.log('')
  logger.log('='.repeat(60))
  logger.log('RESULTS')
  logger.log('='.repeat(60))
  logger.log('')
  logger.log(
    `Tools (uncompressed): ${(totalToolSize / 1024 / 1024).toFixed(2)} MB`,
  )
  logger.log(`Node binary: ${(nodeStats.size / 1024 / 1024).toFixed(2)} MB`)
  if (blobStats) {
    logger.log(`Blob: ${(blobStats.size / 1024 / 1024).toFixed(2)} MB`)
  }
  logger.log(`Final SEA binary: ${finalSizeMB.toFixed(2)} MB`)
  logger.log('')
  logger.log(`Output: ${outputPath}`)
  logger.log('')
  logger.log(
    `Compression: ${compressionRatio}% reduction from uncompressed size`,
  )
  logger.log('')

  return outputPath
}
