import { execSync } from 'node:child_process' // gated test ONLY: detect tool prerequisites; never used in production code
// NOTE: The line above is the single permitted use of node:child_process — it is confined to test setup
// (binary-availability detection) and runs nowhere near production code. We do NOT use it for spawning
// bazel itself.
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import { extractBazelToMaven } from './extract_bazel_to_maven.mts'

const FIXTURE = path.join(
  process.env['HOME'] as string,
  'src',
  'bazel-bench',
  'constructed',
  'java-maven',
)
// Fixture's checked-in rules_jvm_external lockfile is the ground truth.
// canonicalize() below strips the rules_jvm_external-only metadata
// (top-level __AUTOGENERATED__/repositories/etc., per-artifact `sources`
// shasum) so what's compared is the subset our extractor emits.
const GROUND_TRUTH = path.join(FIXTURE, 'maven_install.json')
const INLINE_DECL_TRUTH = path.join(FIXTURE, 'expected-direct-decl.txt')

function bazelAvailable(): boolean {
  try {
    execSync('bazelisk --version', { stdio: 'ignore' })
    return true
  } catch {
    try {
      execSync('bazel --version', { stdio: 'ignore' })
      return true
    } catch {
      return false
    }
  }
}

function javaAvailable(): boolean {
  try {
    execSync('java -version', { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

// Canonicalize: sort artifact keys + dependency arrays, AND strip the
// rules_jvm_external-only fields our extractor doesn't emit (per-artifact
// `sources` shasum; top-level `__AUTOGENERATED__`/`repositories`/etc. are
// already dropped by plucking only `artifacts` + `dependencies`). Lets us
// compare directly against the fixture's checked-in `maven_install.json`.
function canonicalize(o: Record<string, unknown>): {
  artifacts: Record<string, unknown>
  dependencies: Record<string, string[]>
} {
  const artifacts = (o['artifacts'] ?? {}) as Record<
    string,
    { shasums?: Record<string, string>; version?: string }
  >
  const dependencies = (o['dependencies'] ?? {}) as Record<string, string[]>

  const artifactKeys = Object.keys(artifacts).sort()
  const sortedArtifacts: Record<string, unknown> = {}
  for (const k of artifactKeys) {
    const a = artifacts[k] ?? {}
    const jar = a.shasums?.['jar']
    sortedArtifacts[k] = {
      shasums: jar ? { jar } : {},
      version: a.version,
    }
  }

  const depKeys = Object.keys(dependencies).sort()
  const sortedDeps: Record<string, string[]> = {}
  for (const k of depKeys) {
    sortedDeps[k] = [...(dependencies[k] ?? [])].sort()
  }

  return { artifacts: sortedArtifacts, dependencies: sortedDeps }
}

// Inline-decl independent truth: every `g:a:v` line must appear in extracted artifacts (key g:a, version v).
function checkInlineDeclCoverage(
  extracted: { artifacts?: Record<string, { version?: string }> },
  expectedLines: string[],
): { missing: string[] } {
  const missing: string[] = []
  for (const line of expectedLines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) {
      continue
    }
    const lastColon = trimmed.lastIndexOf(':')
    const ga = trimmed.slice(0, lastColon)
    const ver = trimmed.slice(lastColon + 1)
    const got = extracted.artifacts?.[ga]
    if (!got || got.version !== ver) {
      missing.push(
        trimmed +
          (got ? ` (got version ${got.version})` : ' (artifact key absent)'),
      )
    }
  }
  return { missing }
}

describe('extractBazelToMaven against ~/src/bazel-bench/constructed/java-maven', () => {
  const skip =
    !bazelAvailable() ||
    !javaAvailable() ||
    !existsSync(FIXTURE) ||
    !existsSync(GROUND_TRUTH) ||
    !existsSync(INLINE_DECL_TRUTH)

  it.skipIf(skip)(
    'produces an exact-match maven_install.json vs ground truth + recovers all inline-decl artifacts',
    async () => {
      const tmp = mkdtempSync(path.join(os.tmpdir(), 'bazel-constructed-'))
      // Per-test bazel --output_base under tmp so vitest's parallel test
      // files do not collide on the default shared bazel server (each
      // workspace gets its own server keyed by output_base).
      const bazelOutputBase = path.join(tmp, '_bazel_ob')
      try {
        await extractBazelToMaven({
          bin: undefined,
          bazelFlags: undefined,
          bazelOutputBase,
          bazelRc: undefined,
          cwd: FIXTURE,
          out: tmp,
          verbose: !!process.env['VERBOSE_BAZEL_TEST'],
        })

        const extractedPath = path.join(tmp, 'maven_install.json')
        expect(existsSync(extractedPath)).toBe(true)
        const extractedRaw = JSON.parse(
          readFileSync(extractedPath, 'utf8'),
        ) as Record<string, unknown>
        const extracted = canonicalize(extractedRaw)
        const groundTruth = canonicalize(
          JSON.parse(readFileSync(GROUND_TRUTH, 'utf8')) as Record<
            string,
            unknown
          >,
        )

        // ---- Inline-decl independent ground truth (LOAD-BEARING) ----
        const inlineDeclLines = readFileSync(INLINE_DECL_TRUTH, 'utf8').split(
          '\n',
        )
        const { missing: inlineMissing } = checkInlineDeclCoverage(
          extractedRaw as { artifacts?: Record<string, { version?: string }> },
          inlineDeclLines,
        )

        // Write extracted output as evidence (overwrites prior runs).
        writeFileSync(
          path.join(tmp, 'java-maven-extracted.json'),
          JSON.stringify(extracted, null, 2),
          'utf8',
        )

        // Write a diff summary as evidence.
        const groundKeys = new Set(Object.keys(groundTruth.artifacts))
        const extractedKeys = new Set(Object.keys(extracted.artifacts))
        const missing = [...groundKeys].filter(k => !extractedKeys.has(k))
        const extra = [...extractedKeys].filter(k => !groundKeys.has(k))
        const diffLines: string[] = [
          `# socket manifest bazel — constructed fixture exact-match diff`,
          `# Generated: ${new Date().toISOString()}`,
          `# Fixture: ${FIXTURE}`,
          ``,
          `Ground-truth artifact count: ${groundKeys.size}`,
          `Extracted artifact count:    ${extractedKeys.size}`,
          ``,
          `Missing (in ground truth but NOT extracted): ${missing.length}`,
          ...missing.map(k => `  - ${k}`),
          ``,
          `Extra (in extracted but NOT ground truth): ${extra.length}`,
          ...extra.map(k => `  - ${k}`),
          ``,
          `Inline-decl ground truth (independent): ${inlineDeclLines.filter(l => l.trim() && !l.trim().startsWith('#')).length} entries`,
          `Inline-decl artifacts NOT recovered: ${inlineMissing.length}`,
          ...inlineMissing.map(m => `  - ${m}`),
          ``,
          missing.length === 0 &&
          extra.length === 0 &&
          inlineMissing.length === 0
            ? `RESULT: EXACT MATCH (lockfile-derived) + INLINE-DECL COVERED`
            : `RESULT: MISMATCH — extractor needs investigation`,
        ]
        writeFileSync(
          path.join(tmp, 'java-maven-diff.txt'),
          diffLines.join('\n'),
          'utf8',
        )

        expect(missing).toEqual([])
        expect(extra).toEqual([])
        expect(extracted).toEqual(groundTruth)
        // LOAD-BEARING — independent of the lockfile-derived ground truth.
        expect(inlineMissing).toEqual([])
      } finally {
        rmSync(tmp, { recursive: true, force: true })
      }
    },
    300_000,
  ) // 5-minute timeout for cold-cache bazel runs.
})
