[package]
name = "yoga-layout-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Socket Security <hello@socket.dev>"]
description = "Size-optimized Yoga Layout WASM bindings for Socket CLI"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Taffy - Pure Rust flexbox layout engine (Yoga alternative).
taffy = "0.6.0"

# WASM bindings for JavaScript interop.
wasm-bindgen = "0.2.104"

[profile.release]
opt-level = 3
lto = false  # Disabled for WASM cdylib compatibility.
codegen-units = 1

# Maximum aggressive release builds for WASM.
# Use: cargo build --target wasm32-unknown-unknown --profile release-wasm-fast
# NO BACKWARDS COMPATIBILITY - Modern runtimes only!
[profile.release-wasm-fast]
inherits = "release"
opt-level = "z"              # Optimize for size (WASM benefits from smaller size).
lto = "thin"                 # Thin LTO is faster than full, still effective.
codegen-units = 1            # Single unit for release.
strip = true                 # Strip symbols for smaller WASM.
panic = "abort"              # No unwinding (smaller code).
overflow-checks = false      # Remove overflow checks (faster, smaller).
debug-assertions = false     # Remove debug assertions (faster, smaller).
