name: E2E Tests

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e-tests:
    uses: SocketDev/socket-registry/.github/workflows/test.yml@main
    secrets: inherit
    with:
      test-script: 'pnpm run e2e-tests'
      timeout-minutes: 20
