name: 🧪 E2E Tests

on:
  push:
    branches: [main]
    tags: ['*']
    paths:
      - 'packages/cli/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - '.github/workflows/e2e-tests.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - '.github/workflows/e2e-tests.yml'
  workflow_dispatch:
    inputs:
      node-versions:
        description: 'Node.js versions to test (comma-separated)'
        required: false
        type: string
        default: '20,22,24'

permissions:
  contents: read

jobs:
  e2e-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        node-version: ${{ fromJSON(format('[{0}]', inputs.node-versions || '20,22,24')) }}
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest] - Windows tests disbaled (see project https://linear.app/socketdev/project/autofixes-windows-support-fc2f2a45f759)
    steps:
      - uses: SocketDev/socket-registry/.github/actions/setup-and-install@51be85d39d3b4a42dd9d4712948b9d30a2e04794
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build CLI
        working-directory: packages/cli
        run: pnpm run build

      - name: Run e2e tests
        working-directory: packages/cli
        env:
          SOCKET_CLI_API_TOKEN: ${{ secrets.SOCKET_CLI_API_TOKEN }}
        run: pnpm run e2e-tests
