name: Linting

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-check:
    uses: SocketDev/socket-registry/.github/workflows/lint.yml@f5802f78a42b057a830e9f836c8332662b3a40b9 # main
