name: Node CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    # FIXME Replace with socket.dev one
    uses: voxpelli/ghatemplates/.github/workflows/test.yml@main
    with:
      node-versions: '14,16,18'
      os: 'ubuntu-latest,windows-latest'
