name: 📦 Publish socket JS fallback to npm registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.1.25)'
        required: true
        type: string
      dry-run:
        description: 'Dry run (build but do not publish)'
        required: false
        type: boolean
        default: false

jobs:
  publish-socket-js:
    name: Publish socket JS version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@e9540b3eafaf84907c087a645d3258bfaa861427 # v3.0.0
        with:
          version: 8

      - name: Determine version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          # Remove 'v' prefix if present
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: packages/cli
        run: pnpm install --frozen-lockfile

      - name: Build JavaScript distribution
        working-directory: packages/cli
        run: pnpm run build:js

      - name: Update package version
        working-directory: packages/cli
        run: |
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Verify build
        working-directory: packages/cli
        run: |
          # Check that dist files exist
          test -f dist/cli.js || exit 1
          test -f dist/npm-cli.js || exit 1
          test -f dist/npx-cli.js || exit 1
          test -f dist/pnpm-cli.js || exit 1
          test -f dist/yarn-cli.js || exit 1
          echo "✓ All distribution files built successfully"

      - name: Publish to npm
        if: ${{ !inputs.dry-run }}
        working-directory: packages/cli
        run: npm publish --provenance --access public

      - name: Dry run summary
        if: ${{ inputs.dry-run }}
        working-directory: packages/cli
        run: |
          echo "🚫 Dry run mode - package was NOT published"
          echo ""
          echo "Would have published:"
          echo "@socketsecurity/cli@$(jq -r .version package.json)"
