name: Type Checks

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type-check:
    uses: SocketDev/socket-registry/.github/workflows/types.yml@a912e5bd8ec469d2ee13abf592a6b2e5898c006c # main
