name: Type Checks

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type-check:
    uses: SocketDev/socket-registry/.github/workflows/types.yml@5b2880d768d55e61f32213b01e08528b22e649e9 # main
