export const FIREWALL_ENTERPRISE_ECOSYSTEMS = new Map<string, string>([
  ['anaconda.org', 'Conda'],
  ['bioconductor.org', 'Bioconductor (R)'],
  ['builds.hex.pm', 'Hex (Elixir/Erlang)'],
  ['cdn.cocoapods.org', 'CocoaPods'],
  ['center.conan.io', 'Conan (C/C++)'],
  ['cmake.org', 'CMake FetchContent'],
  ['conan.io', 'Conan (C/C++)'],
  ['conda-forge.org', 'Conda'],
  ['conda.anaconda.org', 'Conda'],
  ['cpan.metacpan.org', 'CPAN (Perl)'],
  ['cran.r-project.org', 'CRAN (R)'],
  ['cran.rstudio.com', 'CRAN (R)'],
  ['download.swift.org', 'Swift toolchain'],
  ['downloads.bitnami.com', 'Bitnami'],
  ['hackage.haskell.org', 'Hackage (Haskell)'],
  ['hex.pm', 'Hex (Elixir/Erlang)'],
  ['huggingface.co', 'Hugging Face'],
  ['julialang-s3.julialang.org', 'Julia'],
  ['luarocks.org', 'LuaRocks (Lua)'],
  ['marketplace.visualstudio.com', 'VS Code extensions'],
  ['metacpan.org', 'CPAN (Perl)'],
  ['mirror.bazel.build', 'Bazel'],
  ['ocaml.org', 'opam (OCaml)'],
  ['opam.ocaml.org', 'opam (OCaml)'],
  ['packagist.org', 'Composer (PHP)'],
  ['pkg.julialang.org', 'Julia'],
  ['pub.dev', 'pub.dev (Dart/Flutter)'],
  ['repo.anaconda.com', 'Conda'],
  ['repo.hex.pm', 'Hex (Elixir/Erlang)'],
  ['repo.packagist.org', 'Composer (PHP)'],
  ['swift.org', 'Swift toolchain'],
  ['swiftpackageindex.com', 'Swift Package Index'],
  ['ziglang.org', 'Zig'],
])

export const FIREWALL_ENTERPRISE_INFRASTRUCTURE = new Set([
  'bitbucket.org',
  'gist.githubusercontent.com',
  'gitlab.com',
  'objects.githubusercontent.com',
  'raw.githubusercontent.com',
  'release-assets.githubusercontent.com',
])

export const FIREWALL_FREE_INFRASTRUCTURE = new Set([
  'api.github.com',
  'nodejs.org',
  'npm.fontawesome.com',
])
